# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ingresso-ios-challenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ingresso-ios-challenge
	pod 'Alamofire'
  
  pod 'Kingfisher', '7.0.0-beta.3'


  target 'ingresso-ios-challengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ingresso-ios-challengeUITests' do
    # Pods for testing
  end

end
